databases:
  - name: homebaker
    databaseName: homebaker
    user: kaity

services:
  - type: web
    name: homebaker
    plan: free
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn homebaker.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: homebaker
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: AWS_ACCESS_KEY_ID
        value: placeholder
      - key: AWS_SECRET_ACCESS_KEY
        value: placeholder
      - key: AWS_S3_REGION_NAME
        value: placeholder
      - key: AWS_STORAGE_BUCKET_NAME
        value: placeholder